site_name: 学习笔记
site_url:
docs_dir: 'docs/zh'

nav:
  - Home: index.md
  - About: about.md
  - 数学:
    - 微分算子: math/diff-operators.md
    - 常微分方程:
      - 常微分方程求解: math/ode/ode.md
      - Python求解器: math/ode/ode-python.md
    - 线性系统:
      - math/linear-system/index.md
    - 欧拉公式: math/euler-eq.md
    - 张量: math/tensor.md
    - 偏微分方程:
      - 历史: math/pde/pde-history.md
      - 偏微分方程求解: math/pde/pde.md
    - 伽辽金法: math/galerkin.md
    - 距离度量: math/distances.md
  - 算法:
    - algorithm/index.md
    - 复杂度: algorithm/complexity.md
    - 动态规划:
      - algorithm/dynamic-planning/index.md
  - 语言:
    - Python:
      - languages/python/index.md
    - C++:
      - languages/c++/index.md
    - Rust:
      - languages/rust/index.md
  - 模拟仿真:
    - simulation/index.md
    - 图形学仿真:
      - 弹簧质点系统: simulation/graphics/mss.md
      - 线性有限元: simulation/graphics/lfem.md
      - 物质点法: simulation/graphics/mpm.md
    - 离散事件模拟仿真:
      - simulation/des/index.md
    - 有限元仿真:
      - simulation/fem/index.md
    - 有限状态机:
      - simulation/fsm/index.md
  - 技术概念:
    - CI/CD: tech-concepts/cicd.md
    - MLOps:
      - tech-concepts/mlops/index.md
  - 工具:
    - Git: tools/git.md
    - 谷歌云平台:
      - tools/gcp/index.md

theme:
  name: material # readthedocs
  palette:
    - primary: teal

    # # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode

  navigation_depth: 1
  collapse_navigation: false
  features:
#    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.expand
#    - toc.integrate
    - toc.follow
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.critic # text formatting
  - pymdownx.caret # text formatting
  - pymdownx.keys # text formatting
  - pymdownx.mark # text formatting
  - pymdownx.tilde # text formatting
  - pymdownx.highlight: # code hil
      anchor_linenums: true
  - pymdownx.inlinehilite # code hil
  - pymdownx.snippets # code hil
  - pymdownx.superfences # code hil
  - pymdownx.arithmatex:
      generic: true
  - attr_list # load emoji, load image
  - md_in_html # load image
  - pymdownx.emoji: # load emoji/icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

